core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include("films.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

films/urls.py
from django.urls import path, include

from . views import homepage, film_detail, add_films, add_reviews, top250,bot250, most_votes

app_name = "films"

urlpatterns = [
    path("", homepage, name="home"),
    path("film/<int:pk>/", film_detail, name="f_detail"),
    path("add_films", add_films, name="add_films"),
    path("add_reviews", add_reviews, name="add_reviews"),
    path("top250", top250, name="top250"),
    path("bot250", bot250, name="bot250"),
    path("most_votes", most_votes, name="most_votes"),
]

films/models.py
from django.db import models
from django.conf import settings # Add this line to the the bottom of the imports 

certs = [
    ("U", "U"),
    ("PG", "PG"),
    ("12a", "12a"),
    ("15", "15"),
    ("18", "18"),
]

class Film(models.Model):
    title = models.CharField(max_length=250)
    released = models.DateField(auto_now=False, auto_now_add=False)
    certificate = models.CharField(max_length=3, choices=certs)
    duration = models.DurationField()
    genre = models.CharField(max_length=100)
    director = models.CharField(max_length=250)
    star1 = models.CharField(max_length=250)
    star2 = models.CharField(max_length=250)
    star3 = models.CharField(max_length=250)
    star4 = models.CharField(max_length=250)
    overview = models.TextField(max_length=1000)
    poster = models.URLField(max_length=200)

    def __str__(self):
        return self.title
    
    @property
    def average_rating(self):
        return self.ratings.all().aggregate(models.Avg("rating")).get("rating__avg", 0.0)
    
    @property
    def No_votes(self):
        return self.ratings.all().aggregate(models.Count("rating")).get("rating__count", 0.0)

class Rating(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name="ratings")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField()

    def __str__(self):
        return f"{self.film} - {self.user}"

films/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.db.models import Avg, Count
import os, json
from datetime import timedelta
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from random import randint

from . models import Film, Rating
module_dir = os.path.dirname(__file__)  
# Create your views here.
def top250(request):
    films = Film.objects.annotate(avr=Avg("ratings__rating"), votes=Count("ratings__rating")).order_by("-avr")[0:250]
    paginator = Paginator(films, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"films":films, "page_obj":page_obj}
    return render(request, "films/homepage.html", context)

def most_votes(request):
    films = Film.objects.annotate(avr=Avg("ratings__rating"), votes=Count("ratings__rating")).order_by("-votes")[0:250]
    paginator = Paginator(films, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"films":films, "page_obj":page_obj}
    return render(request, "films/homepage.html", context)

def bot250(request):
    films = Film.objects.annotate(avr=Avg("ratings__rating")).order_by("avr")[0:250]
    paginator = Paginator(films, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"films":films, "page_obj":page_obj}
    return render(request, "films/homepage.html", context)

def add_films(request):
    file_path = os.path.join(module_dir, 'imdb_top_films.json')
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    no_added = 0
    for film in data:
        dur = film["Runtime"]
        f_dur = timedelta(minutes=int(dur[0:-4]))
        obj = Film.objects.update_or_create(
            title = film["Series_Title"],
            released = f"{film['Released_Year']}-01-01",
            certificate = film["Certificate"],
            duration = f_dur,
            genre = film["Genre"],
            director = film["Director"],
            star1 = film["Star1"],
            star2 = film["Star2"],
            star3 = film["Star3"],
            star4 = film["Star4"],
            overview = film["Overview"],
            poster = film["Poster_Link"]
        )
        no_added += 1
    msg = f"Added {no_added} films to the database."
    return HttpResponse(msg, content_type="text/plain")
    
def add_rev(g_film, g_user, g_rating):
    obj, create = Rating.objects.get_or_create(
        film = get_object_or_404(Film, pk=g_film),
        user = get_object_or_404(User, pk=g_user),
        rating = g_rating,
    )

def homepage(request):
    films = Film.objects.all()
    paginator = Paginator(films, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"films":films, "page_obj":page_obj}
    return render(request, "films/homepage.html", context)

def film_detail(request, pk):
    if request.method == "POST":
        obj = Rating.objects.update_or_create(
            film = get_object_or_404(Film, pk=request.POST["film"]),
            user = get_object_or_404(User, pk=request.user.id),
            rating = request.POST["rating"]
        )
        rated = Rating.objects.get(film=request.POST["film"], user=request.user)
        context = {"rating":rated}
        return render(request, 'films/partials/user_review.html', context)
    else:
        film = get_object_or_404(Film, pk=pk)
        if request.user.is_authenticated:
            rating = Rating.objects.filter(user=request.user, film=film).first()
        else:
            rating = ""
        total_seconds= int(film.duration.total_seconds())
        hours = total_seconds//3600
        minutes = (total_seconds % 3600 )//60
        duration = f"{hours}h {minutes}m"
        genres = film.genre.split(",")
        context = {"film":film, "dura":duration, "genres":genres, "rating":rating}
    return render(request, "films/f_detail.html", context)

def add_reviews(request):
    for j in range(0,10000):
        for i in range(1,5):
            filmID = randint(1,692)
            filmRating = randint(1,10)
            add_rev(filmID, i, filmRating)
    return redirect("films:home")

films/templates/films/f_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <h1>{{film.title}}</h1>
    
    <div class="row">
        <div class="col-4">
            <img class="img-fluid" src="{{film.poster}}" alt="">
        </div>
        <div class="col-8">
            <p>
                {% for genre in genres %}
                    <span class="badge rounded-pill text-bg-primary">{{genre}}</span>
                {% endfor %}
            </p>
            <p>{{film.released|date:"Y"}} - {{film.certificate}} - {{dura}}</p>
            <p>{{film.overview}}</p>
            <br>
            <div class="alert alert-light" role="alert">
                <div class="row">
                    <div class="col col-3">
                        IMDB Rating: 
                    </div>
                    <div class="col col-3">
                        <p><i class="bi bi-star-fill text-warning"></i> {{film.average_rating|floatformat:1}}/10</p>
                        <p class="small"> Reviews: {{film.No_votes}}</p>
                    </div>
                    <div class="col col-6">
                        Your Rating: 
                        <div id="user_rating">
                            {% if rating %}                            
                                <i class="bi bi-star-fill text-primary"></i> <span class="mx-3">{{rating.rating}}</span>
                            {% else %}
                                <div x-data="{showModal: false}" x-on:keydown.escape="showModal=false" x-on:click.away="showModal = false">
                                    {% if request.user.is_authenticated %}
                                        <button on.click="showModal = true" class="btn btn-outline-primary" data-bs-toggle="#vote_modal">
                                            <i class="bi bi-star text-warning"></i> <span class="mx-3">Rate</span>
                                        </button>
                                    {% else %}
                                        <a class="btn btn-outline-primary" href="{% url 'login' %}">
                                            <i class="bi bi-star text-warning"></i> <span class="mx-3">Rate</span>
                                        </a>
                                    {% endif %}
                                    
                                    
                                    <div x-show="showModal" class="modal modal-dialog-centered" id="vote_modal" tabindex="-1" aria-hidden="true">
                                        <div class="modal-dialog">
                                          <div class="modal-content">
                                            <div class="modal-header">
                                              <h1 class="modal-title fs-5 text-align-content-center"><span class="text-warning">RATE: </span>{{film.title}}</h1>
                                              <button type="button" class="btn-close" x-on:click="showModal=false" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row d-flex justify-content-center">
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat1" value="1"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML' class="btn btn-primary"> </form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat2" value="2"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat3" value="3"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat4" value="4"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat5" value="5"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat6" value="6"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat7" value="7"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat8" value="8"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat9" value="9"   name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>
                                                    <div class="col-1"><form hx-post="{{request.path}}"> <input type="hidden" name="film" id="film" value="{{film.id}}"> <input type="submit" id="rat10" value="10" name="rating" hx-post="{% url 'films:f_detail' film.id %}" hx-target='#user_rating' hx-swap='innerHTML'  class="btn btn-primary"></form></div>   
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-warning" x-on:click="showModal=false">Cancel</button>
                                            </div>
                                          </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div> 
            </div>
            <br>

            <h2>Top Cast</h2>
            <br>
            <ul class="list-group">
                <li class="list-group-item">{{film.star1}}</li>
                <li class="list-group-item">{{film.star2}}</li>
                <li class="list-group-item">{{film.star3}}</li>
                <li class="list-group-item">{{film.star4}}</li>
            </ul>
            <br>
            <h5>Director: {{film.director}}</h5>
        </div>
    </div>
    
    
{% endblock content %}

films/templates/films/homepage.html
{% extends "base.html" %}

{% block content %} 
    <h1>Kinopiosk</h1>
    <hr>
    
    <div class="row row-cols-5">
    {% for film in page_obj %}
    <div class="mb-3">
        <div class="card bg-body-tertiary" style="min-height: 450px;">
            <a href="{% url 'films:f_detail' film.id %}">
                <img src="{{film.poster}}" class="card-img-top" height="300px" width="200px">
            </a>
            <div class="card-body">
                <h4>
                    <i class="bi bi-star-fill text-warning"></i> <span class="me-5">{{film.avr|floatformat:1}}</span>
                    <i class="bi bi-star text-primary"></i>
                </h4>
                <h5><a class="text-decoration-none" href="{% url 'films:f_detail' film.id %}">{{film.title}}</a></h5>
              
            </div>
        </div>
    </div>
    
    
    <!-- <p><a href="{% url 'films:f_detail' film.id %}">{{film.title}}</a></p> -->
    {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.paginator.1}}">&laquo; first</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                </li>
            {% else %} 
            <li class="page-item disabled">
                <a class="page-link" href="#">&laquo; first</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">previous</a>
            </li>
            {% endif %}
            {% for n in page_obj.paginator.page_range %}
                {% if page_obj.number == n %}

                    <li class="page-item active">
                        <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                {% elif n > page_obj.number|add:-3 and n < page_obj.number|add:3 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">next</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#">last &raquo;</a>
                </li>
            {% endif %}
            </li>
        </ul>
    </nav>        
      
    

{% endblock content %}

films/templates/films/partials/user_review.html
<i class="bi bi-star text-primary"></i> <span class="mx-3">{{rating.rating}}</span>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    {% block css %}{% endblock %}
</head>
<body data-bs-theme="dark" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container">
              <img src="/static/kinopoisk_icon.png" alt="Image">


              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'films:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'films:top250' %}">Top 250</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'films:bot250' %}">Bottom 250</a>
                  </li>
                  
                </ul>
                <div class="d-flex">
                  <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success me-2" type="submit">Search</button>
                  </form>
                  {% if request.user.is_authenticated %}
                    <a class="btn btn-outline-warning" href="{% url 'logout' %}">Logout</a>
                  {% else %}
                    <a class="btn btn-outline-warning" href="{% url 'login' %}">Login</a>
                  {% endif %}
                </div>
                

              </div>
            </div>
          </nav>
    <div class="container">
        {% block content %} {% endblock content %}
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>